---

- name: Install Packages
  package:
    name: "{{ item }}"
  with_items:
    - supervisor
    - python3
    - python3-pip
    - build-essential
    - checkinstall
    - cython3
    - libgcrypt11-dev
    - libgnutls28-dev
    - libudev-dev
    - libyaml-dev
    - python3-dev
    - python3-setuptools
    - python3-sphinx


- name: Install Home Assistant
  pip:
    name: homeassistant
    executable: pip3

- name: Install Python Packages
  pip:
    name: "{{ item }}"
    executable: pip3
  with_items:
    - netdisco
    - pyyaml
    - xmltodict


- name: Start supervisor service
  service:
    name: supervisor
    state: started

- name: Add group
  group:
    name: "{{ homeassistant_group }}"
    system: yes
  when: homeassistant_manage_user

- name: Add user
  user:
    name: "{{ homeassistant_user }}"
    group: "{{ homeassistant_group }}"
    shell: /sbin/nologin
    system: yes
  when: homeassistant_manage_user

- name: Create Home Assistant directory
  file:
    path: "{{ homeassistant_dir }}"
    state: directory
    owner: "{{ homeassistant_user }}"
    group: "{{ homeassistant_group }}"
    recurse: true

- meta: flush_handlers
